### ISSUE TITLE
增加图层

### ISSUE THREAD

**Issue by ChenArno** [Jeff-Bee/onLinePS#1]
大佬，增加图层那块逻辑能放开吗

**Comment by Jeff-Bee** [comment]
有个组件是用于新增图层的  相关方法都有，因为需要保存图片所以先把这一块给去掉了  你可以先看看代码 找不到的我可以给你加个示例

**Comment by ChenArno** [comment]
我这边是看到有个增加图层的页面，但是有个bannerDataTransform工具类缺失，无法串联起来

**Comment by Jeff-Bee** [comment]
那个工具类是我业务处理用的，已经添加了新增图层和文本的入口按钮和实现，你可以仿照着实现自己的业务逻辑，更新代码查看
